apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: eks-charts
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  storageNamespace: kube-system
  install: {}
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 2.4.2
      sourceRef:
        kind: HelmRepository
        name: eks-charts
  values:
    clusterName: "robotshop-cluster"
    serviceAccount:
      name: aws-load-balancer-controller
      create: false
  interval: 10m0s
