apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: eks-charts
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::661516917150:role/AmazonEKSLoadBalancerControllerRole
  name: aws-load-balancer-controller
  namespace: kube-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  storageNamespace: kube-system
  install: {}
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: eks-charts
  values:
    clusterName: "robotshop-cluster"
    serviceAccount:
      name: aws-load-balancer-controller
      create: false
  interval: 10m0s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-gateway
  namespace: istio-system
  annotations:
    # create AWS Application LoadBalancer
    kubernetes.io/ingress.class: alb
    # external type
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP

spec:
  rules:
    - http:
        paths:
          #          - path: /*
          #            backend:
          #              serviceName: ssl-redirect
          #              servicePort: use-annotation
          - path: /healthz/ready
            pathType: Prefix
            backend:
              service:
                name: istio-gateway
                port:
                  number: 15021
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80

#          - backend:
#              service:
#                name: istio-ingressgateway
#                port:
#                  number: 443
#            path: /
#            pathType: Prefix
