apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shipping
  namespace: robot-shop
spec:
  dependsOn:
    - name: base
resources:
  - deployment.yaml
  - service.yaml