apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-elb-controller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./core-system/aws-elb
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system