apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
    - name: external-dns-route53
    - name: aws-elb-controller
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/istio
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-infra-variables
