apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./system-addons/istio
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-infra-variables
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns-route53
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 1m0s
  path: ./system-addons/external-dns-aws-route53
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-elb-controller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./system-addons/aws-loadbalancer-controller
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-autoscaler-controller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./system-addons/cluster-autoscaler
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system