---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-gateway
  dependsOn:
    - name: istio-base
    - name: istiod
  chart:
    spec:
      version: 1.14.1
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
  values:
    autoscaling:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    service:
      type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-gateway
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: "32671"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      # AWS Certificate Manager certificate's ARN
      #alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-3:***:certificate/fcaa9fd2-1b55-48d7-92f2-e829f7bafafd"
    # open ports 80 and 443
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      # redirect all HTTP to HTTPS
    # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # ExternalDNS settings: https://rtfm.co.ua/en/kubernetes-update-aws-route53-dns-from-an-ingress/
    #external-dns.alpha.kubernetes.io/hostname: "istio-test-alb.example.com"

spec:
  rules:
    - http:
        paths:
          #          - path: /*
          #            backend:
          #              serviceName: ssl-redirect
          #              servicePort: use-annotation
          - path: /healthz/ready
            pathType: Prefix
            backend:
              service:
                name: istio-gateway
                port:
                  number: 15021
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-gateway
                port:
                  number: 80

#          - backend:
#              service:
#                name: istio-ingressgateway
#                port:
#                  number: 443
#            path: /
#            pathType: Prefix
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/target: "k8s-istiosys-istiogat-4ef32a305c-984208283.eu-west-1.elb.amazonaws.com"
    external-dns.alpha.kubernetes.io/hostname: "grafana.meraki-mv-rekognition.aws.outscope.com"
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http-grafana
        protocol: HTTP
      hosts:
        - "grafana.meraki-mv-rekognition.aws.outscope.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  hosts:
    - "grafana.meraki-mv-rekognition.aws.outscope.com"
  gateways:
    - grafana-gateway
  http:
    - route:
        - destination:
            host: grafana
            port:
              number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/target: "k8s-istiosys-istiogat-4ef32a305c-984208283.eu-west-1.elb.amazonaws.com"
    external-dns.alpha.kubernetes.io/hostname: "kiali.meraki-mv-rekognition.aws.outscope.com"
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http-kiali
        protocol: HTTP
      hosts:
        - "kiali.meraki-mv-rekognition.aws.outscope.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
    - "kiali.meraki-mv-rekognition.aws.outscope.com"
  gateways:
    - kiali-gateway
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 3000